// All products data - matches schema.ts structure
export const allProducts = [
    {
        id: 1,
        name: "Curso moderno de desenvolvimento full stack com Next.js",
        slug: "modern-full-stack-nextjs-course",
        tagline: "Aprenda a criar aplicações full stack modernas com Next.js",
        description:
            "Aprenda a criar aplicações full stack modernas com Next.js 16.",
        websiteUrl: "https://nextjscourse.dev",
        tags: ["Next.js", "Tailwind CSS", "Full Stack"],
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
        approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "john@example.com",
        voteCount: 120,
    },
    {
        id: 2,
        name: "TaskFlow Pro",
        slug: "taskflow-pro",
        tagline: "Gerencie projetos como nunca antes",
        description:
            "Simplifique o fluxo de trabalho da sua equipe com gestão inteligente de tarefas, notificações automáticas e recursos de colaboração em tempo real.",
        websiteUrl: "https://taskflowpro.example.com",
        tags: ["Produtividade", "SaaS"],
        createdAt: new Date("2024-01-18"),
        approvedAt: new Date("2024-01-19"),
        status: "approved" as const,
        submittedBy: "mike@example.com",
        voteCount: 87,
    },
    {
        id: 3,
        name: "CodeSnap",
        slug: "codesnap",
        tagline: "Belas capturas de código para desenvolvedores",
        description:
            "Crie belas capturas de código com temas personalizáveis, realce de sintaxe e opções de exportação. Ideal para documentação e redes sociais.",
        websiteUrl: "https://codesnap.example.com",
        tags: ["Ferramentas de desenvolvimento", "Design"],
        createdAt: new Date("2024-01-20"),
        approvedAt: new Date("2024-01-21"),
        status: "approved" as const,
        submittedBy: "alex@example.com",
        voteCount: 56,
    },
    {
        id: 4,
        name: "ProofyBubble",
        slug: "proofybubble",
        tagline: "Notificações de prova social que convertem visitantes em clientes",
        description:
            "Aumente as conversões do seu site com notificações de prova social em tempo real. Mostre compras recentes, cadastros e atividades dos usuários para transmitir confiança e credibilidade.",
        websiteUrl: "https://proofybubble.com",
        tags: ["Marketing", "SaaS", "Conversão"],
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
        approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "proofy@example.com",
        voteCount: 523,
    },
    {
        id: 5,
        name: "ParityKit",
        slug: "paritykit",
        tagline: "Paridade de preços para produtos SaaS globais",
        description:
            "Aumente sua receita global com preços adaptados a cada região. Ajuste os valores automaticamente com base na paridade do poder de compra para aumentar as conversões no mundo todo.",
        websiteUrl: "https://paritykit.com",
        tags: ["SaaS", "Precificação", "Global"],
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
        approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "parity@example.com",
        voteCount: 612,
    },
    {
        id: 6,
        name: "DataViz Pro",
        slug: "dataviz-pro",
        tagline: "Transforme seus dados em belas visualizações",
        description:
            "Crie gráficos e painéis interativos a partir de qualquer fonte de dados. Ideal para apresentações, relatórios e análise de dados.",
        websiteUrl: "https://datavizpro.example.com",
        tags: ["Análise de dados", "Design", "SaaS"],
        createdAt: new Date("2024-01-28"),
        approvedAt: new Date("2024-01-29"),
        status: "approved" as const,
        submittedBy: "data@example.com",
        voteCount: 234,
    },
    {
        id: 7,
        name: "EmailCraft",
        slug: "emailcraft",
        tagline: "Marketing por e-mail simples e eficiente",
        description:
            "Crie, envie e acompanhe campanhas de e-mail com nosso editor intuitivo de arrastar e soltar e ferramentas avançadas de automação.",
        websiteUrl: "https://emailcraft.example.com",
        tags: ["Marketing", "E-mail", "SaaS"],
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
        approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "email@example.com",
        voteCount: 378,
    },
    {
        id: 8,
        name: "APIHub",
        slug: "apihub",
        tagline: "Gerencie e monitore todas as suas APIs em um só lugar",
        description:
            "Plataforma centralizada de gestão de APIs com monitoramento em tempo real, documentação e ferramentas de teste. Mantenha todas as suas APIs organizadas e seguras.",
        websiteUrl: "https://apihub.example.com",
        tags: ["Ferramentas de desenvolvimento", "API", "Infraestrutura"],
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
        approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "api@example.com",
        voteCount: 445,
    },
    {
        id: 9,
        name: "Curso de desenvolvedor a líder",
        slug: "developer-to-leader-course",
        tagline: "Aprenda a liderar uma equipe de desenvolvedores",
        description:
            "Aprenda a liderar uma equipe de desenvolvedores e torne-se uma referência na sua área. Este curso foi criado para desenvolvedores que desejam dar o próximo passo na carreira e assumir uma posição de liderança.",
        websiteUrl: "https://developertoleader.com",
        tags: ["Liderança", "Gestão", "Desenvolvimento"],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        status: "approved" as const,
        submittedBy: "kulkarni.ankita09@gmail.com",
        voteCount: 340,
    },
    {
        id: 10,
        name: "Alto desempenho em aplicações .NET",
        slug: "high-performance-in-dot-net-applications",
        tagline: "Aprenda a melhorar o desempenho de aplicações .NET",
        description: "Neste curso, você aprenderá sobre desempenho de aplicações em geral e como criar aplicações .NET com o máximo de eficiência.",
        websiteUrl: "https://developertoleader.com",
        tags: ["Desempenho", ".NET", "Desenvolvimento"],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        status: "pending" as const,
        submittedBy: "paulo.fdo@hotmail.com",
        voteCount: 400,
    },
];